"""empty message

Revision ID: 26783d4b2feb
Revises: 
Create Date: 2023-05-03 23:27:34.623011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26783d4b2feb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('otp', sa.Integer(), nullable=False),
    sa.Column('otp_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.Date(), nullable=False),
    sa.Column('email_recover', sa.String(length=20), nullable=False),
    sa.Column('image_profile', sa.String(length=250), nullable=False),
    sa.Column('security_question_q1', sa.String(length=50), nullable=False),
    sa.Column('security_question_q2', sa.String(length=50), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('coach', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('url_youtube', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=280), nullable=False),
    sa.Column('cover', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cover'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('url_youtube')
    )
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=280), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('token_blocked_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_number', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=20), nullable=True),
    sa.Column('credit_card', sa.String(), nullable=True),
    sa.Column('otp', sa.Integer(), nullable=True),
    sa.Column('otp_active', sa.Boolean(), nullable=True),
    sa.Column('twofa', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.Date(), nullable=True),
    sa.Column('email_recover', sa.Integer(), nullable=True),
    sa.Column('image_profile', sa.String(length=250), nullable=True),
    sa.Column('security_question_q1', sa.String(length=50), nullable=True),
    sa.Column('security_question_q2', sa.String(length=50), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('height', sa.Float(precision=10), nullable=True),
    sa.Column('weight', sa.Float(precision=10), nullable=True),
    sa.Column('other_sports', sa.String(length=20), nullable=True),
    sa.Column('level_training', sa.String(length=20), nullable=True),
    sa.Column('eating_habits', sa.String(length=20), nullable=True),
    sa.Column('injuries', sa.String(length=100), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('email_subscription', sa.Boolean(), nullable=True),
    sa.Column('numeric_preference', sa.String(length=10), nullable=True),
    sa.Column('access_gym', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('body_fat', sa.Float(), nullable=False),
    sa.Column('muscle_mass', sa.Float(), nullable=False),
    sa.Column('water_intake', sa.Integer(), nullable=False),
    sa.Column('calories_intake', sa.Integer(), nullable=False),
    sa.Column('protein_intake', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('exercise_number', sa.String(length=20), nullable=False),
    sa.Column('load', sa.Float(precision=10), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('rest_time', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('date_finished', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('training_days', sa.String(length=50), nullable=False),
    sa.Column('rest_days', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('body_fat', sa.Float(), nullable=True),
    sa.Column('muscle_mass', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress')
    op.drop_table('calendar')
    op.drop_table('programs')
    op.drop_table('nutrition')
    op.drop_table('favoritos')
    op.drop_table('user')
    op.drop_table('token_blocked_list')
    op.drop_table('papers')
    op.drop_table('exercises')
    op.drop_table('events')
    op.drop_table('employees')
    # ### end Alembic commands ###
