"""empty message

Revision ID: e4c7b19c4b9a
Revises: ab0c5c0d9748
Create Date: 2023-05-20 13:25:32.377714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c7b19c4b9a'
down_revision = 'ab0c5c0d9748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_by_ia', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_chat', schema=None) as batch_op:
        batch_op.drop_column('generated_by_ia')

    # ### end Alembic commands ###
